# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Dependencies

#highlighter: pygments

# Build settings
markdown: kramdown

# Site settings
title: RandomvBites
tagline: "Just Another Random IT Blog"
description: 'Random vBites grabbing some bites and nibbles of knowledge.
  Contacts <a href="https://twitter.com/ricardonadao" target="_blank">@ricardonadao</a> or <a href="mailto:ricardo.adao@gmail.com">email</a>
'
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://randomvbites.github.io" # the base hostname & protocol for your site

email: ricardo.adao@gmail.com
twitter_username: ricardonadao
github_username:  randomvbites

#Custom Vars
version: 1.0

# Jekyll Config
host: 0.0.0.0
port: 4000
incremental: true

