# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RandomvBites
email: ricardo.adao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random vBites is no more that some random bites of knowledge.\n
  You can contact me <a href="https://twitter.com/ricardonadao" target="_blank">@ricardonadao</a> or <a href="mailto:ricardo.adao@gmail.com">email</a>
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://randomvbites.github.io" # the base hostname & protocol for your site
twitter_username: ricardonadao
github_username:  randomvbites

# Build settings
markdown: kramdown
