# Dependencies markdown: redcarpet
markdown: kramdown highlighter: pygments gems: [jekyll-paginate]
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
#relative_permalinks: true
# Setup
title: RandomvBites tagline: "Ricardo's crappy site" description: 'Alex Pearson''s technical 
IT blog <a href="http://www.vrandom.com" target="_blank">www.vrandom.com</a>. Contact me on 
<a href="https://twitter.com/alexpearson" target="_blank">@alexpearson</a> or <a 
href="mailto:alex@apics.co.uk">email</a>.' url: http://www.vrandom.com
#baseurl: /
paginate: 10
# About/contact
author:
  name: Alex Pearson
  url: https://twitter.com/alexpearson
  email: alex@apics.co.uk
# Custom vars
version: 1.0.0
